name: pocket_manager
description: A single-player, offline-first football management game skeleton.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/content/
